#!/bin/bash

#This file is transferred to a Debian/Ubuntu Host and executed to re-map interfaces
#Extra config COULD be added here but I would recommend against that to keep this file standard.
echo "#################################"
echo "   Provisioning Has Begun"
echo "#################################"

sudo su
#mv script and set permissions
mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp
chmod +x /etc/init.d/rename_eth_swp
#make sure script is setup to run on boot
/usr/sbin/update-rc.d rename_eth_swp start 45 S .

#mv interface renaming file into place on disk
mv /home/vagrant/remap_eth /etc/default/remap_eth


#Create Start up script for the Vagrant and ETH0 Interface
sed -i '/exit 0/d' /etc/rc.local
echo -e "/sbin/ifdown eth0" >> /etc/rc.local
echo -e "/etc/init.d/rename_eth_swp" >> /etc/rc.local
echo -e "/sbin/ifup eth0 &" >> /etc/rc.local
echo -e "/sbin/ifup vagrant" >> /etc/rc.local
echo -e "exit 0\n" >> /etc/rc.local


#remove cloud-init software
apt-get purge cloud-init -y

#Remove existing interfaces file
rm /etc/network/interfaces
#Remove default Eth0 config
rm /etc/network/interfaces.d/eth0.cfg

#Replace existing network interfaces file
echo -e "auto lo" >> /etc/network/interfaces
echo -e "iface lo inet loopback\n\n" >> /etc/network/interfaces
echo -e  "source /etc/network/interfaces.d/*.cfg\n" >> /etc/network/interfaces

#Add vagrant interface
echo -e "\n\nauto vagrant" >> /etc/network/interfaces.d/vagrant.cfg
echo -e "iface vagrant inet dhcp\n\n" >> /etc/network/interfaces.d/vagrant.cfg

#Add eth0 interface
echo -e "\n\nauto eth0" >> /etc/network/interfaces.d/eth0.cfg
echo -e "iface eth0 inet dhcp\n\n" >> /etc/network/interfaces.d/eth0.cfg


echo "#################################"
echo "   Finished and Rebooting"
echo "#################################"
#reboot machine
reboot &
