#!/bin/bash

#This file is transferred to a Debian/Ubuntu Host and executed to re-map interfaces
#Extra config COULD be added here but I would recommend against that to keep this file standard.
echo "#################################"
echo "   Provisioning Has Begun"
echo "#################################"

sudo su
#mv script and set permissions
mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp
chmod +x /etc/init.d/rename_eth_swp
#make sure script is setup to run on boot
/usr/sbin/update-rc.d rename_eth_swp start 45 S .

#mv interface renaming file into place on disk
mv /home/vagrant/remap_eth /etc/default/remap_eth

#Create Start up script for the Vagrant Interface
#echo -e "/sbin/ifup vagrant" >> /etc/init.d/start_vagrant
#chmod +x /etc/init.d/start_vagrant
#/usr/sbin/update-rc.d start_vagrant start 60 S .


#Make Local Script
sed -i '/exit 0/d' /etc/init.d/start_vagrant
echo -e "/sbin/ifdown eth0" >> /etc/init.d/start_vagrant
echo -e "/sbin/ifdown eth1" >> /etc/init.d/start_vagrant
echo -e "/etc/init.d/rename_eth_swp" >> /etc/init.d/start_vagrant
echo -e "/sbin/ifup vagrant" >> /etc/init.d/start_vagrant
echo -e "/sbin/ifup eth0" >> /etc/init.d/start_vagrant
echo -e "exit 0\n" >> /etc/init.d/start_vagrant
chmod +x /etc/init.d/start_vagrant
/usr/sbin/update-rc.d start_vagrant start 60 S .

#Remove existing interfaces file
rm /etc/network/interfaces
#Remove default Eth0 config
rm /etc/network/interfaces.d/eth0.cfg

#Replace existing network interfaces file
echo -e "auto lo" >> /etc/network/interfaces
echo -e "iface lo inet loopback\n\n" >> /etc/network/interfaces
echo -e  "source /etc/network/interfaces.d/*.cfg\n" >> /etc/network/interfaces

#Add vagrant interface
echo -e "\n\nauto vagrant" >> /etc/network/interfaces.d/vagrant.cfg
echo -e "iface vagrant inet dhcp\n\n" >> /etc/network/interfaces.d/vagrant.cfg

#Configure ip address on eth0
echo -e "\nauto eth0\niface eth0 inet static\n    address 192.168.207.254\n    netmask 255.255.255.0\n" >> /etc/network/interfaces.d/eth0.cfg

#remove cloud-init software
apt-get purge cloud-init -y

#Installations
apt-get install -y software-properties-common
apt-add-repository -y ppa:ansible/ansible
apt-get update -y
apt-get install -y ansible git isc-dhcp-server tree apache2 python-pip shedskin libyaml-dev sshpass

ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""

cp /root/.ssh/id_rsa.pub /var/www/html/cumulus1.pub

cp /home/vagrant/hosts /etc/hosts

cp /home/vagrant/dhcp_vagrant.conf /etc/dhcp/dhcpd.conf

echo "#################################"
echo "   Finished and Rebooting"
echo "#################################"

#reboot machine
reboot &
